### ISSUE TITLE
The claim about DSACK causing security issues is not actually backed by evidence

### ISSUE THREAD

**Issue by mikkorantalainen** [Kicksecure/security-misc#107]
The comment here

https://github.com/Kicksecure/security-misc/blob/c19942f72b8d74056dd8da8c3cd9ac7e0fbe8991/etc/sysctl.d/tcp_sack.conf#L1-L2

makes it appear as if using DSACK would be a security problem. However, the discussion linked doesn't seem to provide any evidence for this. The linked SUSE material only speaks about disabling DSACK in 10 Gbit networks to reduce CPU usage.

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/disabling-tcp-sack-dsack-fack/8109/10

**Comment by adrelanos** [comment]
//cc @madaidan

**Comment by raja-grewal** [comment]
https://forums.whonix.org/t/disabling-tcp-sack-dsack-fack/8109/10

**Comment by adrelanos** [comment]
Thanks!

**Comment by adrelanos** [comment]
//cc @madaidan

**Comment by adrelanos** [comment]
Still some leftovers here:
https://github.com/Kicksecure/security-misc/blob/master/README.md?plain=1#L385

Would you like to update?
