### ISSUE TITLE
Linux security

### ISSUE THREAD

**Issue by Lin-Admin** [Kicksecure/security-misc#123]
Your main activity is silencing any critiques.
And BTW, in your publication [(https://madaidans-insecurities.github.io/linux.html)] you pretend that Linux is completely insecure, of course not telling in a single word how many good additions are available.
Hopefully nobody will finance you...

**Comment by adrelanos** [comment]
Wrong inbox.

* I am not @madaidan.
* I don't maintain the `madaidans-insecurities.github.io` website.
